### PR TITLE
SCMOD-5065: Resolve Vulnerability issues 

### PR DESCRIPTION
**Pull request by thilagasanthosh**
http://sou-jenkins2.hpeswlab.net/job/CAFDataProcessing/view/Developer/job/CAFDataProcessing~data-processing-initialization~SCMOD-5065~CI/

### CODE REVIEW

**Comment by michael-bryson** [comment]
@thilagasanthosh I cannot see the vulnerability issues so cannot check that the changes are correct. Please get someone else to review these.

**Comment by thilagasanthosh** [comment]
@michael-bryson ,
Please find the email alert for issues.

[Vulnerabiliy_issue.zip](https://github.com/CAFDataProcessing/data-processing-initialization/files/2755189/Vulnerabiliy_issue.zip)

**Comment by michael-bryson** [comment]
I cannot see if the issues are resolved as I do not see the alerts at the top of the screen in GitHub. You need someone who does have access to these alerts to review this.

**Comment by thilagasanthosh** [comment]
@andyreidz , Please confirm no vulnerability issue alerts reported from Github after this fix.

**Review by andyreidz — APPROVED** [review]

**Pull request merged**
